from exceptions.exceptions import ServiceError


class UserNotFound(ServiceError):
    pass
